functionsDirectory = "C:\\Users\\rocco\\dev\\royi2-stack\\royi2-backend\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\rocco\\dev\\royi2-stack\\royi2-backend"
publishOrigin = "default"
functions = "C:\\Users\\rocco\\dev\\royi2-stack\\royi2-backend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]